name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 동작

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Set up Azure CLI
      uses: azure/cli@v1
      with:
        inlineScript: az --version
    
    - name: Login to Azure using Service Principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up kubelogin
      uses: azure/setup-kubelogin@v1

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group rg-yeo --name aks-idp-demo --overwrite-existing
    
    - name: Deploy to Kubernetes
      run: kubectl apply -f aks-store-all-in-one.yaml -n pets

    - name: Check Pods Status
      run: |
        kubectl get pods -n pets
      continue-on-error: true